#!/bin/bash
set -Eeuo pipefail

rm -rf 16.0/base_requirements.txt
wget https://raw.githubusercontent.com/camptocamp/docker-odoo-project/master/16.0/base_requirements.txt -O 16.0/base_requirements.txt

rm -rf 15.0/base_requirements.txt
wget https://raw.githubusercontent.com/camptocamp/docker-odoo-project/master/15.0/base_requirements.txt -O 15.0/base_requirements.txt

rm -rf 14.0/base_requirements.txt
wget https://raw.githubusercontent.com/camptocamp/docker-odoo-project/master/14.0/base_requirements.txt -O 14.0/base_requirements.txt

rm -rf 13.0/base_requirements.txt
wget https://raw.githubusercontent.com/camptocamp/docker-odoo-project/master/13.0/base_requirements.txt -O 13.0/base_requirements.txt

rm -rf 12.0/base_requirements.txt
wget https://raw.githubusercontent.com/camptocamp/docker-odoo-project/master/12.0/base_requirements.txt -O 12.0/base_requirements.txt

echo "File have been updated from C2C project, please check it 'git diff' and remove marabunta/anthem tools"
