#!/bin/bash

if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
then
    echo "Database does not exist, ignoring script"
    exit 0
fi

if [ "$( psql -tAc "SELECT 1 FROM information_schema.tables WHERE table_name='queue_job'" )" ]
then
    echo "Queue Job not installed, ignoring script"
    exit 0
fi

echo "Resetting enqueued and started jobs to pending"
psql --quiet << EOF
  UPDATE queue_job SET state = 'pending' WHERE state in ('started', 'enqueued')
EOF
