#!/bin/bash
set -ex
cd /odoo
# ak clone + ak sparse will retrieve only the wanted directories
ak clone
ak sparse
ak build
# clean useless file
cd /odoo/external-src
rm -rf */.git*
find . -type f -name ".*" -delete
find . -type f -name "oca_dependencies.txt" -delete
rm -rf */setup
if [[ $BUILD_RESTRICT_LANG ]]
then
    find . -name *.po ! -name $BUILD_RESTRICT_LANG -type f -exec rm -v {} +
fi
