#!/bin/bash
set -e
cd /odoo

ak build -c odoo-spec.yaml -f odoo-frozen.yaml
# Clean useless file

# Remove useless git directory
rm -rf /odoo/src/.git

# Keep only wanted odoo module if defined
if [ -z "$(ls -A /odoo/links)" ]; then
  echo "No module specify, display all"
else
  cp -r -L /odoo/links /odoo/odoo-addons
  rm -rf /odoo/src/addons/*
  mv /odoo/odoo-addons/* /odoo/src/addons
fi

# Secondly we remove unwanted lang
if [[ BUILD_RESTRICT_LANG ]]
then
    find /odoo/src/ -name *.po ! -name $BUILD_RESTRICT_LANG -type f -exec rm -v {} +
fi
